name: CI (pilotsuite-styx-core)

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/pilotsuite-dev/github-action-shared.yml
    with:
      repo-name: "pilotsuite-styx-core"
      repo-path: "pilotsuite-dev/pilotsuite-styx-core"
