name: Production Guard (pilotsuite-styx-core)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  critical-path:
    uses: ./.github/workflows/pilotsuite-dev/github-action-shared.yml
    with:
      repo-name: "pilotsuite-styx-core"
      repo-path: "pilotsuite-dev/pilotsuite-styx-core"
